### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by parpwhick** [tedyapo/loopfield#7]
Except for the Helmholtz configuration, the other two examples are not working out of the box

**Comment by tedyapo** [comment]
Thanks for the report. Please provide more information about exactly what is not working for you and the versions of python, numpy, scipy, and matplotlib you are using.  I just tried this on a fresh install of lubuntu 17.10 using the following, and all three examples work:

sudo apt-get install virtualenv
virtualenv -p python3 LF
source LF/bin/activate
pip install loopfield
git clone https://www.github.com/tedyapo/loopfield
cd loopfield/examples
./helmholtz_coil.py
./maxwell_coil.py
./single_loop.py

**Comment by parpwhick** [comment]
Thank you for the response! Using virtualenv (and probably much fresher packages thanks to pip), the maxwell coil example works. 

The `single_loop.py` still does not work. 
```
LF/lib/python3.5/site-packages/numpy/core/numeric.py:1120: RuntimeWarning: invalid value encountered in multiply
  return multiply(a.ravel()[:, newaxis], b.ravel()[newaxis,:], out)
B =  [inf nan nan]
```

**Comment by tedyapo** [comment]
The warning is expected behavior. This is a limitation of the mathematical model. Evaluating the magnetic field at a point on the loop produces an infinite result; this is a non-physical situation which is not covered by the model.  If you want to suppress the warning generated by numpy during evaluation of points like this, you can use something like:

```python
import numpy as np
...
with np.errstate(invalid='ignore'):
  B = field.evaluate([0., radius, 0.])
print('B = ', B)
```
If you use the library, you should be aware of this possibility, and consider how you wish to handle it in your own code.

Note that one could argue the value returned should be [inf, 0, 0], but I believe chasing the corner cases to this level of detail is likely to result in fragile code.

**Comment by parpwhick** [comment]
I'm sorry. I didn't notice that the singleloop example was not supposed to output any images. I thought the errors prevented the script from running, and that's why I reported them to you.

**Comment by tedyapo** [comment]
I think it's an indication that the examples could use some more documentation.

Thanks for your interest, and for reporting the issue!
